### ISSUE TITLE
Member Directory Not Loading For Android

### ISSUE THREAD

**Issue by mestrada03** [TAMUSHPE/MobileApp#419]
### Oveview
Android version of the app does not load member directory properly once user scrolls to the bottom. Talk to Jason in regards to possible issue.

**Comment by LucientZ** [comment]
This bug occurs due to scroll throttling of the scrollviews:
```js
<ScrollView
    onScroll={handleScroll}
    scrollEventThrottle={200}
    showsVerticalScrollIndicator={false}
>
```

Because the throttling is 200 milliseconds (0.2 seconds), if a user on an Android device happens to reach the bottom of the `ScrollView` within that 0.2 second interval, they are technically no longer scrolling, meaning the callback is not called. This would have to be fixed by either lowering the throttle and figure out a good sweet-spot with extensive testing, or turning off throttling all together.
