### ISSUE TITLE
Collecting Student Information

### ISSUE THREAD

**Issue by mestrada03** [TAMUSHPE/MobileApp#440]
### Overview
TAMU SHPE collects data from students such gender, GPA, major, expected graduation time, and more. The statistics are used in the best interest of the organization.

### Task
- [ ] add the link and instruction to membershpe screen

**Comment by LucientZ** [comment]
We're already collecting some of these. What exactly does this issue entail?

**Comment by JasonIsAzn** [comment]
> We're already collecting some of these. What exactly does this issue entail? Are we adding more fields?

There is a lot of other information that they need to gather (race, gpa, gender, DOB, etc). This [form](https://docs.google.com/forms/d/e/1FAIpQLSeJqnOMHljOHcMGVzkhQeVtPgt5eG5Iic8vZlmZjXCYT0qw3g/viewform?edit2=2_ABaOnudFPcIvjv6DgDYOjXkAchm6I8i2J_0pBFRM-SvnMcaWcfsZ042nzFt6or-RrA&fbzx=4709315589379606968)shows all the information they need.

The deadline for this would be by this weekend. Since we don't have enough time to come up with a solution + implement it. We are just going to give out the form similar to last year and add it add an instruction to fill the form out.

In the future, we will need a more permanent solution, so we don't have to collect the information externally.
